/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.actividads
 */
export class Actividad { 
    id: number;
    nombreActividad?: string;
    idTActividadA?: number;
    idFrecuenciaA?: number;
    idEvidenciaA?: number;
    idSistemaEvaluacion?: number;
    idIdoneidadInstructor?: number;
    idconsolidadoPlan?: number;
    presupuesto?: number;
}
