/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.asistencia
 */
export class Asistencia { 
    idAsistencia: number;
    fecha?: string;
    cedula?: number;
    idActividad?: number;
    estado?: number;
}
