/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.consolidado_presupuesto
 */
export class Consolidadopresupuesto { 
    id: number;
    numeroDocumento?: string;
    nombre?: string;
    idElaborado?: number;
    fechaElaborado?: string;
    idRevisado?: number;
    fechaRevisado?: string;
    idAprobado?: number;
    firmaAprobado?: string;
    descripcion?: string;
    idEmpresa?: number;
}
