/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.consolidadoplan
 */
export class Consolidadoplan { 
    idconsolidadoPlan: number;
    numeroDocumento?: string;
    elaboradoPor?: number;
    fechaElaboracion?: string;
    revisadoPor?: number;
    fechaRevisado?: string;
    descripcionPlan?: string;
    aprobadoPor?: number;
    firmaAprobado?: string;
    empresa?: number;
}
