/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.consolidado_plan
 */
export class Consolidadoplan { 
    id: number;
    numeroDocumento?: string;
    elaboradoPor?: number;
    fechaElaboracion?: string;
    revisadoPor?: number;
    fechaRevisado?: string;
    descripcion?: string;
    idAprobadoPor?: number;
    firmaAprobado?: string;
    idEmpresa?: number;
}
