/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.consolidadopresupuesto
 */
export class Consolidadopresupuesto { 
    idconsolidadoPresupuesto: number;
    numeroDocumentoP?: string;
    nombrePresupuesto?: string;
    elaboradoPor?: number;
    fechaElaborado?: number;
    revisadoPor?: number;
    fechaRevisado?: number;
    aprobadoPor?: number;
    firmaAprobado?: string;
    descripcion?: string;
    idEmpresa?: number;
}
