/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ciudad } from './ciudad';
import { Tipoempresa } from './tipoempresa';


/**
 * sst.empresas
 */
export class Empresa { 
    id: number;
    nit?: string;
    razonSocial?: string;
    telefono?: number;
    direccion?: string;
    logo?: string;
    actividadComercial?: string;
    tipoEmpresa?: Tipoempresa;
    ciudad?: Ciudad;
}
