/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.estadoplan
 */
export interface Estadoplan { 
    idEstadoPlan: number;
    idActividadE?: number;
    fechaE?: string;
    estado?: number;
    evidenciaEntrega?: string;
    observaciones?: string;
}
