/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.estado_recurso
 */
export class Estadorecurso { 
    id: number;
    idRecurso?: number;
    fecha?: string;
    estado?: number;
    evidencia?: string;
    observaciones?: string;
}
