/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.tipoactividads
 */
export class Tipoactividad { 
    id: number;
    nombreTActividad?: string;
    meta?: string;
    objetivo?: string;
}
