/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * sst.usuario
 */
export class Usuario { 
    cedula: number;
    nombreUsuario?: string;
    correo?: string;
    celular?: number;
    idCiudadU?: number;
    idCargoU?: number;
    idTipoContrato?: number;
}
