/**
 * API SST
 * Api para aplicaciones del proyecto SST
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Empresa } from '../model/empresa';
import { ErrorModel } from '../model/errorModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EmpresasService {

    protected basePath = 'https://localhost/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Trae todas las empresas
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public empresaGet(observe?: 'body', reportProgress?: boolean): Observable<Array<Empresa>>;
    public empresaGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Empresa>>>;
    public empresaGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Empresa>>>;
    public empresaGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Empresa>>(`${this.basePath}/empresa`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Trae una empresa por id
     * 
     * @param idEmpresa id de la empresa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public empresaIdEmpresaGet(idEmpresa: number, observe?: 'body', reportProgress?: boolean): Observable<Empresa>;
    public empresaIdEmpresaGet(idEmpresa: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Empresa>>;
    public empresaIdEmpresaGet(idEmpresa: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Empresa>>;
    public empresaIdEmpresaGet(idEmpresa: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idEmpresa === null || idEmpresa === undefined) {
            throw new Error('Required parameter idEmpresa was null or undefined when calling empresaIdEmpresaGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Empresa>(`${this.basePath}/empresa/${encodeURIComponent(String(idEmpresa))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Editar un tipo empresa por id
     * 
     * @param idEmpresa id de la empresa
     * @param empresa 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public empresaIdEmpresaPut(idEmpresa: number, empresa?: any, observe?: 'body', reportProgress?: boolean): Observable<Empresa>;
    public empresaIdEmpresaPut(idEmpresa: number, empresa?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Empresa>>;
    public empresaIdEmpresaPut(idEmpresa: number, empresa?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Empresa>>;
    public empresaIdEmpresaPut(idEmpresa: number, empresa?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idEmpresa === null || idEmpresa === undefined) {
            throw new Error('Required parameter idEmpresa was null or undefined when calling empresaIdEmpresaPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Empresa>(`${this.basePath}/empresa/${encodeURIComponent(String(idEmpresa))}`,
            empresa,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Crea un registro de empresa
     * 
     * @param empresa 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public empresaPost(empresa: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public empresaPost(empresa: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public empresaPost(empresa: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public empresaPost(empresa: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (empresa === null || empresa === undefined) {
            throw new Error('Required parameter empresa was null or undefined when calling empresaPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/empresa`,
            empresa,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
